### ISSUE TITLE
The coordinates requested are not on the image.

### ISSUE THREAD

**Issue by wmwv** [eyaruss/SURF2017#3]
1. The coordinates `( 195.1287,  20.526425)`
are not on the image.  The result of the aperture photometry is thus NaN.

The snippet of the output

```
229.00858
20.526425
Out[2]:
<SkyCoord (ICRS): (ra, dec) in deg
    ( 195.1287,  20.526425)>
```

indicates that the coordinates are not being loaded correctly.

I believe the error is because the unit for RA is being given as `u.hourangle` when it appears to be 
`u.deg`.

2.  These are not the coordinates you want, in any case.  They are something like the center of the image.  But you want the photometry at the location of the supernova.

**Comment by eyaruss** [comment]
Ok. So I should get the coordinates from DR1 (observed_info text file) and not from the header?

**Comment by wmwv** [comment]
Yes.

But take a moment to understand why one shouldn't have expect the header to have contained the information you were looking for.  The RA, DEC in the header is just the coordinates of the center of the image.  That's unlikely to be the position of the supernova.

Even if the image stamp was extracted centered around the supernova, it is very unlikely to be exactly centered on the supernova down to the pixel.

**Comment by eyaruss** [comment]
Understood. I will work on this and see what I can do. Thank you!
