### ISSUE TITLE
Estimate photon noise uncertainty from non-sky-subtracted data.

### ISSUE THREAD

**Issue by wmwv** [eyaruss/SURF2017#4]
@eyaruss 

pixel_error should be estimated from non-sky-subtracted data.

The pixel error is being estimated from the sky-subtracted data.  These data have an average value of 0, and thus many negative values.  Thus the aperture flux measured is NaN.

**Comment by eyaruss** [comment]
How does pixel_error affect my aperture sum though? It's not a necessary keyword. I can run the code without it and get the same problem.

**Comment by wmwv** [comment]
Because each of #3 and #4 are sufficient to result in NaN.  Both will have been corrected to yield finite values.

MWV

**Comment by eyaruss** [comment]
Is the non-sky-subtracted data in the data file as well? or do I have to find it somewhere else?

**Comment by wmwv** [comment]
No.  Looking into this a bit deeper, I would instead recommend estimating the sky noise based on the variance in the image data itself.  Using the `sqrt` of the image data is a due to the assumption of Poisson noise in the sky background (a good assumption).  But the sky model subtracted is a smooth function, so the noise is still present.  So you can determine the variance in a given region of the image (one with no astrophysical sources) and take the `sqrt` of that as the noise.
